x-environment-defaults: &environment-defaults
  DB_NAME: "backend"
  DB_USER: "backend"
  DB_PASSWORD: "backend"
  DB_HOST: "postgres"
  DB_PORT: 5432

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./users
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/static
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000/api/healthcheck || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./vue-project
    ports:
      - "3000:80"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./users
    command: celery -A users.celery:app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults

  celery-beat:
    build:
      context: ./users
    command: celery -A users.celery:app beat --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults

  flower:
    build:
      context: ./users
    command: celery -A users.celery:app flower
    depends_on:
      - redis
      - postgres
    ports:
      - "5555:5555"

volumes:
  static_volume:

